version: '3.9'

services:
  form_app:
    container_name: form_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - form_network
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      form_mongodb:
        condition: service_healthy

  form_mongodb:
    image: mongo:latest
    env_file:
      - ./.env.dev
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


networks:
  form_network:

volumes:
  mongodb_data:
