version: '3.8'

services:
  form_app:
    container_name: form_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - form_network
    env_file:
      - ./.env.dev
    depends_on:
      form_mongodb:
        condition: service_healthy

  form_mongodb:
    image: mongo:latest
    volumes:
      - ./fill_test_db.py:/docker-entrypoint-initdb.d/fill_test_db.py:ro
      - mongodb_data:/var/lib/mongodb/data/

    env_file:
      - ./.env.dev
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - form_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


networks:
  form_network:

volumes:
  mongodb_data:
